Repository Async-Swift/AsyncSwift-web, pull requests merged in 2022-11, with the labels that each got.

#36 Fix : 텍스트 수정
  pages/Main/Sponsor.js
Labels: Fix

#38 37 fix 연사자 정보 수정
  pages/Main/Speaker.js
  public/speaker/이민아 외 4인.png
  public/speaker/이수진.png
Labels: Fix

#40 Feat/speakers
  .yarn/install-state.gz
  pages/Main/Main.js
  pages/Main/Organizar.js
  pages/Main/Speaker.js
  pages/components/Grid/Organizer/OrganizerGrid.js
  pages/components/Grid/Organizer/OrganizerProfile.js
  pages/components/Grid/Speaker/SpeakerCard.js
  pages/components/Grid/SpeakerGrid.js
  pages/components/Grid/SpeakerProfile.js
  public/organizer/곽세진.png
  public/organizer/김예빈.png
  public/organizer/김은영.png
  public/organizer/김인섭.png
  public/organizer/송시원.png
  public/organizer/윤성관.png
  public/organizer/이민아.png
  public/organizer/이성노.png
  public/organizer/이수진.png
  public/organizer/이현호.png
  public/organizer/최미진.png
  public/organizer/최인호.png
  public/organizer/황예은.png
  public/speaker/강훈.png
  public/speaker/김윤재.png
  public/speaker/김은영.png
  public/speaker/김인섭.png
  public/speaker/김지홍.png
  public/speaker/김찬우.png
  public/speaker/류성두.png
  public/speaker/문상봉.png
  public/speaker/박건호.png
  public/speaker/박종호.png
  public/speaker/백수영.png
  public/speaker/신동준.png
  public/speaker/이가은.png
  public/speaker/이명환.png
  public/speaker/이수진.png
  public/speaker/이준영.png
  public/speaker/이현호.png
  public/speaker/주협.png
  public/speaker/허성진.png
  public/speaker/홍길동.png
  styles/modules/Organizer.module.css
  styles/modules/Speaker.module.css
Labels: enhancement, style

#42 Timeline mobile 이미지를 수정했습니다.
  pages/Main/Conference.js
  pages/Main/Main.js
  pages/Main/Organizar.js
  pages/Main/Sponsor.js
  pages/Main/TimeLine.js
  public/organizer/곽세진.png
  public/organizer/이민아.png
  public/timetable/TT.png
  public/timetable/TTM.png
  styles/modules/TimeLine.module.css
Labels: enhancement, style, refactor, Fix

#43 Develop
  .yarn/install-state.gz
  pages/Main/Conference.js
  pages/Main/Main.js
  pages/Main/Organizar.js
  pages/Main/Speaker.js
  pages/Main/Sponsor.js
  pages/Main/TimeLine.js
  pages/components/Grid/Organizer/OrganizerGrid.js
  pages/components/Grid/Organizer/OrganizerProfile.js
  pages/components/Grid/Speaker/SpeakerCard.js
  pages/components/Grid/SpeakerGrid.js
  pages/components/Grid/SpeakerProfile.js
  public/organizer/곽세진.png
  public/organizer/김예빈.png
  public/organizer/김은영.png
  public/organizer/김인섭.png
  public/organizer/송시원.png
  public/organizer/윤성관.png
  public/organizer/이민아.png
  public/organizer/이성노.png
  public/organizer/이수진.png
  public/organizer/이현호.png
  public/organizer/최미진.png
  public/organizer/최인호.png
  public/organizer/황예은.png
  public/speaker/강훈.png
  public/speaker/김윤재.png
  public/speaker/김은영.png
  public/speaker/김인섭.png
  public/speaker/김지홍.png
  public/speaker/김찬우.png
  public/speaker/류성두.png
  public/speaker/문상봉.png
  public/speaker/박건호.png
  public/speaker/박종호.png
  public/speaker/백수영.png
  public/speaker/신동준.png
  public/speaker/이가은.png
  public/speaker/이명환.png
  public/speaker/이수진.png
  public/speaker/이준영.png
  public/speaker/이현호.png
  public/speaker/주협.png
  public/speaker/허성진.png
  public/speaker/홍길동.png
  public/timetable/TT.png
  public/timetable/TTM.png
  styles/modules/Organizer.module.css
  styles/modules/Speaker.module.css
  styles/modules/TimeLine.module.css
Labels: enhancement, Fix

#45 44 hotfix 잘못된 정보수정
  pages/Main/Speaker.js
  public/timetable/TT.png
  public/timetable/TTM.png
Labels: Fix
