Repository Async-Swift/AsyncSwift-web, pull requests merged in 2022-10, with the labels that each got.

#9 V2 첫 메인 온보딩 제작
  pages/Onboarding/Onboarding.js
  pages/Onboarding/OnboardingScript.js
  pages/components/Description.js
  pages/components/HeadMeta.js
  pages/components/Header.js
  pages/components/SNS.js
  pages/components/Ticket.js
  pages/index.js
  public/birds/hBG.svg
  public/birds/s1.svg
  public/birds/vBG.svg
  public/logo-horizental.svg
  styles/global.css
  styles/modules/Description.module.css
  styles/modules/Header.module.css
  styles/modules/Info.module.css
  styles/modules/Onboarding.module.css
  styles/modules/error.module.css
Labels: enhancement

#12 Main image resize / contents edit
  pages/Footer/Footer.js
  public/AsyncLogo.png
  public/AsyncSwiftLogo.png
  public/LogoHorizental.png
  public/birds/hBG.png
  public/birds/vBG.png
  public/default.png
  public/instagram.png
  public/linkedin.png
  public/notion.png
  public/speaker/강훈.png
  public/speaker/김윤재.png
  public/speaker/김은영.png
  public/speaker/김인섭.png
  public/speaker/김지홍.png
  public/speaker/김찬우.png
  public/speaker/류성두.png
  public/speaker/문상봉.png
  public/speaker/박건호.png
  public/speaker/박종호.png
  public/speaker/백수영.png
  public/speaker/신동준.png
  public/speaker/이가은.png
  public/speaker/이명환.png
  public/speaker/이민아 외 4인.png
  public/speaker/이준영.png
  public/speaker/이현호.png
  public/speaker/주협.png
  public/speaker/허성진.png
  public/speaker/홍길동.png
  public/twitter.png
  public/youtube.png
  styles/modules/Info.module.css
Labels: Fix

#24 17 fix 배경 이미지 수정
  styles/modules/Onboarding.module.css
Labels: Fix

#23 Design: 문단 하이픈 적용시 단어단위로 끊기게 적용
  styles/modules/Description.module.css
Labels: style

#22 Design: 헤더 이미지를 수정했습니다.
  public/LogoHorizental.png
Labels: style

#26 25 feat 연사 이미지정보 추가하기
  pages/Main/Speaker.js
  public/speaker/김지홍.png
  public/speaker/주협.png
Labels: style

#32 Fix: fix sponser layout in mobile
  pages/Main/Sponsor.js
  styles/modules/Main.module.css
  styles/modules/Sponsor.module.css
Labels: style, Fix
